spring:
  application:
    name: Rated Power Challenge

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:in-memory-db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=false;
    username: sa
    password: sa