DROP TABLE IF EXISTS PRICES;

CREATE TABLE IF NOT EXISTS PRICES (
    BRANDID INT NOT NULL,
    STARTDATE TIMESTAMP NOT NULL,
    ENDDATE TIMESTAMP NOT NULL,
    PRICELIST INT NOT NULL,
    PRODUCTID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE VARCHAR NOT NULL,
    CURR VARCHAR NOT NULL,
    CONSTRAINT PRICES_FK PRIMARY KEY (PRODUCTID)
);